pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - author=camblybot
      - check-success=Build
    actions:
      merge:
        method: squash
