name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Check exports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: |
          pnpm run build
          pnpm run check-exports
        env:
          NODE_OPTIONS: --max-old-space-size=8192

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm exec prettier --check .
        env:
          NODE_OPTIONS: --max-old-space-size=8192

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: cd packages/syntax-design-tokens && pnpm run build
        env:
          NODE_OPTIONS: --max-old-space-size=8192
      - run: pnpm run lint
        env:
          NODE_OPTIONS: --max-old-space-size=8192

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm run stylelint
        env:
          NODE_OPTIONS: --max-old-space-size=8192

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: cd packages/syntax-design-tokens && pnpm run build
        env:
          NODE_OPTIONS: --max-old-space-size=8192
      - run: pnpm run test
        env:
          NODE_OPTIONS: --max-old-space-size=8192
